DROP TABLE USERS;
DROP TABLE REVIEW;
DROP TABLE GAME;

DROP SEQUENCE USER_NO;
DROP SEQUENCE GAME_NO;
DROP SEQUENCE RV_NO;

CREATE SEQUENCE USER_NO NOCACHE;
CREATE SEQUENCE GAME_NO NOCACHE;
CREATE SEQUENCE RV_NO NOCACHE;



-- 유저 번호, 아이디, 비밀번호, 이름, 이메일
CREATE TABLE USERS (
   USER_NO NUMBER PRIMARY KEY,
   USER_ID VARCHAR2(2000) UNIQUE NOT NULL,
   USER_PW VARCHAR2(2000) NOT NULL,
   USER_NAME VARCHAR2(2000) NOT NULL,
   USER_EMAIL VARCHAR2(2000) UNIQUE NOT NULL,
   USERENABLED VARCHAR2(2) NOT NULL,
   CONSTRAINT USER_ENABLED_CHK CHECK( USERENABLED IN('Y','N'))
);


INSERT INTO USERS
VALUES(USER_NO.NEXTVAL, 'USER1', 'USER1', '유저1', 'user1@naver.com' , 'Y');

-- 리뷰 번호, 리뷰에 작성한 유저 아이디, 게임 번호, 별점, 내용, 작성일자, 플랫폼 번호
-- RV_USER_ID는 USERS 테이블의 USER_ID의 컬럼을 참조
-- RV_GAME_NO는 GAME 테이블의 GAME_NO의 컬럼을 참조
-- RV_PLATFORM GAME 테이블의 GAME_PLATFORM의 컬럼을 참조 
CREATE TABLE REVIEW (
   RV_NO NUMBER PRIMARY KEY,
   RV_USER_ID VARCHAR2(2000) NOT NULL,
   RV_GAME_NO NUMBER NOT NULL,
   RV_STAR NUMBER NOT NULL,
   RV_CONTENT VARCHAR2(2000) NOT NULL,
   RV_DATE DATE,
   RV_PLATFORM NUMBER,
   CONSTRAINT USER_ID_FK FOREIGN KEY (RV_USER_ID) REFERENCES USERS (USER_ID),
   CONSTRAINT GAME_NO_FK FOREIGN KEY (RV_GAME_NO) REFERENCES GAME (GAME_NO)
);


— 게임 번호, 별 평점, 플랫폼, 게임이름, 회사, 장르, 출시일자, 요약(content)
CREATE TABLE GAME(
   GAME_NO NUMBER PRIMARY KEY,
   GAME_STARAVG NUMBER,
   GAME_PLATFORM NUMBER,
   GAME_NAME VARCHAR2(2000),
   GAME_COMPANY VARCHAR2(2000),
   GAME_GENRE NUMBER,
   GAME_RELEASE DATE,
   GAME_CONTENT VARCHAR2(4000)
);

SELECT * FROM REVIEW;
SELECT * FROM GAME;
SELECT * FROM USERS;