DROP TABLE USERS;
DROP TABLE REVIEW;
DROP TABLE GAME;
DROP TABLE URL;
DROP TABLE M_CONTENT;

DROP SEQUENCE USER_NO;
DROP SEQUENCE GAME_NO;
DROP SEQUENCE RV_NO;
DROP SEQUENCE URL_GAME_NO;

select * from game;
select * from url;

CREATE SEQUENCE USER_NO NOCACHE;
CREATE SEQUENCE GAME_NO NOCACHE;
CREATE SEQUENCE RV_NO NOCACHE;
CREATE SEQUENCE URL_GAME_NO;

CREATE TABLE USERS (
      USER_NO NUMBER PRIMARY KEY,
      USER_ID VARCHAR2(50) UNIQUE NOT NULL,
      USER_PW VARCHAR2(50) NOT NULL,
      USER_NAME VARCHAR2(50) NOT NULL,
      USER_EMAIL VARCHAR2(50) UNIQUE NOT NULL,
      USER_ENABLED VARCHAR2(2) NOT NULL,
      USER_COUNT NUMBER NOT NULL,
   CONSTRAINT USER_ENABLED_CHK CHECK( USER_ENABLED IN ('Y', 'N'))
);


CREATE TABLE REVIEW (
   RV_NO NUMBER PRIMARY KEY,
   RV_USER_ID VARCHAR2(50) NOT NULL,
   RV_GAME_NO NUMBER NOT NULL,
   RV_STAR NUMBER NOT NULL,
   RV_CONTENT VARCHAR2(100) NOT NULL,
   RV_DATE DATE,
   RV_PLATFORM NUMBER
);


CREATE TABLE GAME(
   GAME_NO NUMBER PRIMARY KEY,
   GAME_STARAVG NUMBER,
   GAME_PLATFORM NUMBER CHECK (GAME_PLATFORM IN ('1', '2', '3', '4')),
   GAME_NAME VARCHAR2(4000),
   GAME_COMPANY VARCHAR2(4000),
   GAME_GENRE NUMBER,
   GAME_RELEASE DATE,
   GAME_CONTENT VARCHAR2(4000)
);


CREATE TABLE URL(
   URL_GAME_NO NUMBER PRIMARY KEY,
   MAIN_IMAGE VARCHAR2(4000),
   IMAGE1 VARCHAR2(4000),
   IMAGE2 VARCHAR2(4000),
   IMAGE3 VARCHAR2(4000),
   IMAGE4 VARCHAR2(4000),
   VIDEO1 VARCHAR2(4000),
   VIDEO2 VARCHAR2(4000),
   VIDEO3 VARCHAR2(4000),
   VIDEO4 VARCHAR2(4000),
   VIDEO_IMAGE1 VARCHAR2(4000),
   VIDEO_IMAGE2 VARCHAR2(4000),
   VIDEO_IMAGE3 VARCHAR2(4000),
   VIDEO_IMAGE4 VARCHAR2(4000),
   VIDEO_TITLE1 VARCHAR2(1000),
   VIDEO_TITLE2 VARCHAR2(1000),
   VIDEO_TITLE3 VARCHAR2(1000),
   VIDEO_TITLE4 VARCHAR2(1000),
   ARTICLE1 VARCHAR2(4000),
   ARTICLE2 VARCHAR2(4000),
   ARTICLE3 VARCHAR2(4000),
   A_IMAGE1 VARCHAR2(500),
   A_IMAGE2 VARCHAR2(500),
   A_IMAGE3 VARCHAR2(500),
   ARTICLE_TITLE1 VARCHAR2(2000),
   ARTICLE_TITLE2 VARCHAR2(2000),
   ARTICLE_TITLE3 VARCHAR2(2000),
   ARTICLE_SUMMARY1 VARCHAR2(2000),
   ARTICLE_SUMMARY2 VARCHAR2(2000),
   ARTICLE_SUMMARY3 VARCHAR2(2000),
   PACKAGE_IMG VARCHAR2(500),
   CONSTRAINT GAME_NO_FK FOREIGN KEY (URL_GAME_NO) REFERENCES GAME(GAME_NO)
);


CREATE TABLE M_CONTENT (
   M_GAME_NO NUMBER PRIMARY KEY,
   GAME_PLATFORM NUMBER CHECK (GAME_PLATFORM IN ('1', '2', '3', '4')),
   M_GAME_NAME VARCHAR2(500),
   M_GAME_COMPANY VARCHAR2(1000),
   M_GAME_SUMMARY VARCHAR2(2000),
   M_GAME_SLIDEIMAGE VARCHAR2(500),
   M_GAME_IMAGE VARCHAR2(500)
);

SELECT * FROM GAME;

SELECT * FROM URL;

SELECT * FROM M_CONTENT;

SELECT * FROM USERS;

UPDATE USERS SET USER_PW = '123'  WHERE USER_ID = '아이디11'
